data:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4
    num_classes: 10

model:
    model_type: "ddpm"
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    b: 0
    c: 1
    ckpt_dir: "/home/keeeehun/source/dpm-solver-levy/train_levy2.0_score/logs/ckpt.pth"

diffusion:
    alpha: 2.0
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 128
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 20000
    validation_freq: 2000

sampling:
    total_N: 1000
    schedule: "linear"
    batch_size: 5000
    last_only: True
    # fid_stats_dir: "fid_stats/fid_stats_cifar10_train.npz"
    fid_batch_size: 1000
    cond_class: false
    classifier_scale: 0.0
    h: 0.9

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
